export enum ErrorCode {
  // Generic errors
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',

  // Todo specific errors
  TODO_NOT_FOUND = 'TODO_NOT_FOUND',
  TODO_CREATION_FAILED = 'TODO_CREATION_FAILED',
  TODO_UPDATE_FAILED = 'TODO_UPDATE_FAILED',
  TODO_DELETE_FAILED = 'TODO_DELETE_FAILED',

  // Database errors
  DATABASE_CONNECTION_ERROR = 'DATABASE_CONNECTION_ERROR',
  DATABASE_OPERATION_FAILED = 'DATABASE_OPERATION_FAILED',

  // Cache errors
  CACHE_ERROR = 'CACHE_ERROR',
}
